use anyhow::{Context, Result};
use std::io::{Read, Write};

// age is the maintained interoperable encryption format; this module defines
// no encryption primitive or unauthenticated bespoke envelope.
pub fn encrypt(bytes: &[u8], passphrase: &str) -> Result<Vec<u8>> {
    let encryptor = age::Encryptor::with_user_passphrase(age::secrecy::SecretString::from(
        passphrase.to_owned(),
    ));
    let mut encrypted = Vec::new();
    let mut writer = encryptor.wrap_output(&mut encrypted)?;
    writer.write_all(bytes)?;
    writer.finish()?;
    Ok(encrypted)
}
pub fn decrypt(bytes: &[u8], passphrase: &str) -> Result<Vec<u8>> {
    let decryptor = age::Decryptor::new(bytes)
        .context("INVALID_RECOVERY: expected an age-encrypted Zavliq bundle")?;
    let identity =
        age::scrypt::Identity::new(age::secrecy::SecretString::from(passphrase.to_owned()));
    let mut reader = decryptor
        .decrypt(std::iter::once(&identity as &dyn age::Identity))
        .context("RECOVERY_DECRYPTION_FAILED: incorrect passphrase or corrupted bundle")?;
    let mut plaintext = Vec::new();
    reader
        .read_to_end(&mut plaintext)
        .context("RECOVERY_DECRYPTION_FAILED: bundle authentication failed")?;
    Ok(plaintext)
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn recovery_roundtrip_and_wrong_password() {
        let secret = b"account credentials and room keys";
        let encrypted = encrypt(secret, "long test passphrase 123").unwrap();
        assert!(!encrypted.windows(secret.len()).any(|v| v == secret));
        assert_eq!(
            decrypt(&encrypted, "long test passphrase 123").unwrap(),
            secret
        );
        assert!(decrypt(&encrypted, "wrong test passphrase 456").is_err());
    }
    #[test]
    fn browser_age_export_contains_interoperable_matrix_room_keys() {
        // Public synthetic fixture generated by the independent browser age
        // implementation and Matrix Rust WASM. No live account is involved.
        let encrypted = include_bytes!("../../../apps/web/fixtures/recovery-interoperability.age");
        let pass = "public interoperability fixture password";
        let raw = decrypt(encrypted, pass).unwrap();
        let bundle: serde_json::Value = serde_json::from_slice(&raw).unwrap();
        assert_eq!(bundle["format"], "zavliq-recovery-v1");
        assert_eq!(bundle["handle"], "fixture");
        assert_eq!(bundle["registration_secret"], "f".repeat(64));
        let keys = matrix_sdk_crypto::decrypt_room_key_export(
            std::io::Cursor::new(bundle["room_keys"].as_str().unwrap()),
            pass,
        )
        .unwrap();
        assert_eq!(keys.len(), 1);
        assert_eq!(keys[0].room_id.as_str(), "!interop:localhost");
    }
}
